# Generated by Django 5.2.4 on 2025-07-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_populate_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.location'),
        ),
    ]
