version: '3.8'

services:
  web:
    build: .
    command: >
      /app/launch-dev.sh
    stop_signal: SIGINT
    volumes:
      - ./src:/app/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - MAP_CENTER_LAT=53.8008
      - MAP_CENTER_LNG=-1.5491
      - MAP_ZOOM_LEVEL=13
      - MAP_BOUNDS_MIN_LAT=53.7431222
      - MAP_BOUNDS_MAX_LAT=53.9288420
      - MAP_BOUNDS_MIN_LNG=-1.7116827
      - MAP_BOUNDS_MAX_LNG=-1.3859940
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
