# Generated by Django 5.2.4 on 2025-07-22 21:03

from django.db import migrations

def populate_locations(apps, schema_editor):
    Business = apps.get_model('places', 'Business')
    Location = apps.get_model('places', 'Location')
    for business in Business.objects.all():
        location, created = Location.objects.get_or_create(
            latitude=business.latitude,
            longitude=business.longitude
        )
        business.location = location
        business.save(update_fields=['location'])

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_location_business_location'),
    ]

    operations = [
        migrations.RunPython(populate_locations),
    ]
