# Generated by Django 5.2.4 on 2025-08-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_business_latitude_remove_business_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('osm_type', models.CharField(choices=[('NODE', 'Node'), ('WAY', 'Way'), ('RELATION', 'Relation')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('amenity', models.CharField(max_length=255)),
                ('tags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Imported Places',
                'unique_together': {('osm_id', 'osm_type')},
            },
        ),
    ]
