# Generated by Django 5.2.4 on 2025-09-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_importedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedplace',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.location'),
        ),
    ]
