name: Django Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'

    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        uv-version: '0.7.19'
        enable-cache: true

    - name: Install PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y libpq-dev

    - name: Install dependencies
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      working-directory: ./src
      env:
        POSTGRES_DB: test_db
        POSTGRES_USER: runner
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
      run: uv run python manage.py test
